version: '3'

services: 
  app:
    image: docker.io/ossuchas/happyrefundapi:${TAG}
    build:
        context: .
        dockerfile: ./Dockerfile
    ports: 
      - "5000:5000"
    expose:
      - "4200"
