version: '3'

services: 
  app:
<<<<<<< HEAD
    image: docker.io/apthailand/suchat_s:happyrefund_api_v1.0.1
=======
    image: docker.io/ossuchas/happyrefundapi:v1.22.3
>>>>>>> 5846511cae6ac0f20c4afc4b06e547fa3202ddaf
    build:
        context: .
        dockerfile: ./Dockerfile
    ports: 
      - "5000:5000"
    expose:
      - "5000"
